### ISSUE TITLE
Choose the dataset 

### ISSUE THREAD

**Issue by sherlockliang888** [sherlockliang888/image_classification#1]
For this project, we need to decide the dataset we are working on. It needs to contain more than 800 images with more than 5 classes. Ideally, the dataset contains more than 1000 images and more than 10 classes.

**Comment by sherlockliang888** [comment]
https://www.kaggle.com/slothkong/10-monkey-species

**Comment by sherlockliang888** [comment]
https://www.kaggle.com/chaosxinwei/starter-10-monkey-species-with-keras

**Comment by esevim** [comment]
> https://www.kaggle.com/chaosxinwei/starter-10-monkey-species-with-keras

This is a good one, another method to the one we've seen in class.
